spring.application.name=onlineVoting
spring.datasource.url=jdbc:mysql://localhost:3306/OnlineVoting?createDatabaseIfNotExist=true

# 2. Database Username & Password (Replace with your local MySQL credentials)
spring.datasource.username=spring
spring.datasource.password=password

# 3. MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate / JPA Settings
# 'update' automatically updates your database tables if you change your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update

# 5. Show SQL (highly recommended for debugging)
# This prints the actual SQL queries Hibernate writes for you into the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 6. Database Dialect (Tells Hibernate exactly what flavor of SQL to speak)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#server.port=8081
#spring.security.user.name=admin
#spring.security.user.password={noop}admin
#spring.main.lazy-initialization=true
logging.level.org.springframework=DEBUG
# Force the default auto-configured security chain to disable CSRF 
#spring.security.filter.dispatcher-types=
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration